# Generated by Django 2.1.5 on 2019-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(max_length=4)),
                ('coreqs', models.ManyToManyField(related_name='co', to='schedule.Course')),
                ('prereqs', models.ManyToManyField(related_name='pre', to='schedule.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursesTaken', models.ManyToManyField(to='schedule.Course')),
            ],
        ),
    ]
