# Generated by Django 2.1.5 on 2019-01-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190126_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='co', to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='pre', to='schedule.Course'),
        ),
    ]
